import { HockeyDataKnockoutStage } from '@valcome/ts-hockeydata-api';
import { HockeyDataKnockoutStageMapper } from '../lib/mapper/hockeydata-knockout-stage.mapper';
import { HockeyDataKnockoutPhaseMapper } from '../lib/mapper/hockeydata-knockout-phase.mapper';
import { HockeyDataKnockoutEncounterMapper } from '../lib/mapper/hockeydata-knockout-encounter.mapper';
import { HockeyDataKnockoutTeamScoreMapper } from '../lib/mapper/hockeydata-knockout-team-score.mapper';
import { HockeyDataScheduledGameMapper } from '../lib/mapper/hockeydata-scheduled-game-mapper';
import { HockeyDataGameScoreMapper } from '../lib/mapper/hockeydata-game-score.mapper';
import { IHockeyDataKnockOutStage } from '../lib/model/types';


export class HockeyDataTestData {
  public static createKnockoutStage(): HockeyDataKnockoutStage {

    const knockoutGameScoreMapper = new HockeyDataGameScoreMapper();
    const knockoutGamesMapper = new HockeyDataScheduledGameMapper(knockoutGameScoreMapper);
    const knockoutTeamScoreMapper = new HockeyDataKnockoutTeamScoreMapper();
    const knockoutEncounterMapper = new HockeyDataKnockoutEncounterMapper(knockoutGamesMapper, knockoutTeamScoreMapper);
    const knockoutPhaseMapper = new HockeyDataKnockoutPhaseMapper(knockoutEncounterMapper);
    const knockoutStageMapper = new HockeyDataKnockoutStageMapper(knockoutPhaseMapper);

    return knockoutStageMapper.fromJson(this.getRawKnockoutStageData().data);
  }

  private static getRawKnockoutStageData(): IHockeyDataKnockOutStage {
    return {
      statusId: 1,
      statusMsg: 'Ok',
      data: {
        divisionName: 'ICE Play Offs 2020/21',
        phases: [
          {
            divisionId: 8260,
            divisionName: 'Quarter Finals',
            divisionType: 30,
            encounters: [
              {
                id: 8261,
                longname: 'QF1',
                shortname: null,
                isDecided: false,
                labels: [],
                bestOf: 7,
                gamesNeeded: 5,
                teams: [
                  {
                    id: 193,
                    longname: 'HCB Südtirol Alperia',
                    shortname: 'HCB',
                    gamesWon: 1,
                    encounterTeamStatus: 1
                  },
                  {
                    id: 28176,
                    longname: 'iClinic Bratislava Capitals',
                    shortname: 'BRC',
                    gamesWon: 1,
                    encounterTeamStatus: 2
                  }
                ],
                games: [
                  {
                    id: 'c63b7e97-f13e-4677-9557-875cf6a178a6',
                    scheduledDate: {
                      sortValue: 1615576500000,
                      value: '12.03.2021',
                      shortValue: '12.03.',
                      longValue: '12. March 2021'
                    },
                    scheduledTime: '20:15',
                    gameName: '271',
                    gameDay: null,
                    gameRound: 55,
                    gameUtcTimestamp: 1615576500000,
                    awayTeamId: 28176,
                    awayTeamLongName: 'iClinic Bratislava Capitals',
                    awayTeamShortName: 'BRC',
                    awayTeamFlavourname: 'BRC',
                    homeTeamId: 193,
                    homeTeamLongName: 'HCB Südtirol Alperia',
                    homeTeamShortName: 'HCB',
                    homeTeamFlavourname: 'HCB',
                    homeTeamScore: 1,
                    awayTeamScore: 2,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3600,
                    gameHasEnded: true,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '0:1'
                  },
                  {
                    id: 'dffe8f13-b7c4-4e06-8ffe-36f9ecc934c7',
                    scheduledDate: {
                      sortValue: 1615745700000,
                      value: '14.03.2021',
                      shortValue: '14.03.',
                      longValue: '14. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '275',
                    gameDay: null,
                    gameRound: 56,
                    gameUtcTimestamp: 1615745700000,
                    awayTeamId: 193,
                    awayTeamLongName: 'HCB Südtirol Alperia',
                    awayTeamShortName: 'HCB',
                    awayTeamFlavourname: 'HCB',
                    homeTeamId: 28176,
                    homeTeamLongName: 'iClinic Bratislava Capitals',
                    homeTeamShortName: 'BRC',
                    homeTeamFlavourname: 'BRC',
                    homeTeamScore: 2,
                    awayTeamScore: 7,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3470,
                    gameHasEnded: false,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '1:1'
                  },
                  {
                    id: '5241c371-887c-4403-97cf-b8d1dace4af9',
                    scheduledDate: {
                      sortValue: 1615922100000,
                      value: '16.03.2021',
                      shortValue: '16.03.',
                      longValue: '16. March 2021'
                    },
                    scheduledTime: '20:15',
                    gameName: '279',
                    gameDay: null,
                    gameRound: 57,
                    gameUtcTimestamp: 1615922100000,
                    awayTeamId: 28176,
                    awayTeamLongName: 'iClinic Bratislava Capitals',
                    awayTeamShortName: 'BRC',
                    awayTeamFlavourname: 'BRC',
                    homeTeamId: 193,
                    homeTeamLongName: 'HCB Südtirol Alperia',
                    homeTeamShortName: 'HCB',
                    homeTeamFlavourname: 'HCB',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '33eea502-2ac2-410b-96cb-721efc6f024e',
                    scheduledDate: {
                      sortValue: 1616182200000,
                      value: '19.03.2021',
                      shortValue: '19.03.',
                      longValue: '19. March 2021'
                    },
                    scheduledTime: '20:30',
                    gameName: '283',
                    gameDay: null,
                    gameRound: 58,
                    gameUtcTimestamp: 1616182200000,
                    awayTeamId: 193,
                    awayTeamLongName: 'HCB Südtirol Alperia',
                    awayTeamShortName: 'HCB',
                    awayTeamFlavourname: 'HCB',
                    homeTeamId: 28176,
                    homeTeamLongName: 'iClinic Bratislava Capitals',
                    homeTeamShortName: 'BRC',
                    homeTeamFlavourname: 'BRC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'bfe5650e-f5fb-4a4d-b073-1433dfb8a373',
                    scheduledDate: {
                      sortValue: 1616346900000,
                      value: '21.03.2021',
                      shortValue: '21.03.',
                      longValue: '21. March 2021'
                    },
                    scheduledTime: '18:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616346900000,
                    awayTeamId: 28176,
                    awayTeamLongName: 'iClinic Bratislava Capitals',
                    awayTeamShortName: 'BRC',
                    awayTeamFlavourname: 'BRC',
                    homeTeamId: 193,
                    homeTeamLongName: 'HCB Südtirol Alperia',
                    homeTeamShortName: 'HCB',
                    homeTeamFlavourname: 'HCB',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'f0098f88-0c1e-465e-a2b2-bdc2d4f328fb',
                    scheduledDate: {
                      sortValue: 1616520600000,
                      value: '23.03.2021',
                      shortValue: '23.03.',
                      longValue: '23. March 2021'
                    },
                    scheduledTime: '18:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616520600000,
                    awayTeamId: 193,
                    awayTeamLongName: 'HCB Südtirol Alperia',
                    awayTeamShortName: 'HCB',
                    awayTeamFlavourname: 'HCB',
                    homeTeamId: 28176,
                    homeTeamLongName: 'iClinic Bratislava Capitals',
                    homeTeamShortName: 'BRC',
                    homeTeamFlavourname: 'BRC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '13ad7446-6fdb-4841-ae21-efdeaea3ad7f',
                    scheduledDate: {
                      sortValue: 1616786100000,
                      value: '26.03.2021',
                      shortValue: '26.03.',
                      longValue: '26. March 2021'
                    },
                    scheduledTime: '20:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616786100000,
                    awayTeamId: 28176,
                    awayTeamLongName: 'iClinic Bratislava Capitals',
                    awayTeamShortName: 'BRC',
                    awayTeamFlavourname: 'BRC',
                    homeTeamId: 193,
                    homeTeamLongName: 'HCB Südtirol Alperia',
                    homeTeamShortName: 'HCB',
                    homeTeamFlavourname: 'HCB',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  }
                ]
              },
              {
                id: 8262,
                longname: 'QF2',
                shortname: null,
                isDecided: false,
                labels: [],
                bestOf: 7,
                gamesNeeded: 5,
                teams: [
                  {
                    id: 184,
                    longname: 'EC-KAC',
                    shortname: 'KAC',
                    gamesWon: 1,
                    encounterTeamStatus: 1
                  },
                  {
                    id: 185,
                    longname: 'EC GRAND Immo VSV',
                    shortname: 'VSV',
                    gamesWon: 1,
                    encounterTeamStatus: 2
                  }
                ],
                games: [
                  {
                    id: 'f2b4d5ea-4920-4bbd-9ea7-1fc30a686181',
                    scheduledDate: {
                      sortValue: 1615573800000,
                      value: '12.03.2021',
                      shortValue: '12.03.',
                      longValue: '12. March 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '272',
                    gameDay: null,
                    gameRound: 55,
                    gameUtcTimestamp: 1615573800000,
                    awayTeamId: 185,
                    awayTeamLongName: 'EC GRAND Immo VSV',
                    awayTeamShortName: 'VSV',
                    awayTeamFlavourname: 'VSV',
                    homeTeamId: 184,
                    homeTeamLongName: 'EC-KAC',
                    homeTeamShortName: 'KAC',
                    homeTeamFlavourname: 'KAC',
                    homeTeamScore: 5,
                    awayTeamScore: 1,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3600,
                    gameHasEnded: true,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '1:0'
                  },
                  {
                    id: 'a715b046-6dbc-497f-a5f0-3d291e54d2a9',
                    scheduledDate: {
                      sortValue: 1615739400000,
                      value: '14.03.2021',
                      shortValue: '14.03.',
                      longValue: '14. March 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '276',
                    gameDay: null,
                    gameRound: 56,
                    gameUtcTimestamp: 1615739400000,
                    awayTeamId: 184,
                    awayTeamLongName: 'EC-KAC',
                    awayTeamShortName: 'KAC',
                    awayTeamFlavourname: 'KAC',
                    homeTeamId: 185,
                    homeTeamLongName: 'EC GRAND Immo VSV',
                    homeTeamShortName: 'VSV',
                    homeTeamFlavourname: 'VSV',
                    homeTeamScore: 6,
                    awayTeamScore: 3,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3600,
                    gameHasEnded: false,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '1:1'
                  },
                  {
                    id: '7a36c49a-1ac2-4409-8087-a5d07f9118e8',
                    scheduledDate: {
                      sortValue: 1615919400000,
                      value: '16.03.2021',
                      shortValue: '16.03.',
                      longValue: '16. March 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '280',
                    gameDay: null,
                    gameRound: 57,
                    gameUtcTimestamp: 1615919400000,
                    awayTeamId: 185,
                    awayTeamLongName: 'EC GRAND Immo VSV',
                    awayTeamShortName: 'VSV',
                    awayTeamFlavourname: 'VSV',
                    homeTeamId: 184,
                    homeTeamLongName: 'EC-KAC',
                    homeTeamShortName: 'KAC',
                    homeTeamFlavourname: 'KAC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '6901fa69-c3f1-43f1-95d0-877840e3ff3b',
                    scheduledDate: {
                      sortValue: 1616177700000,
                      value: '19.03.2021',
                      shortValue: '19.03.',
                      longValue: '19. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '284',
                    gameDay: null,
                    gameRound: 58,
                    gameUtcTimestamp: 1616177700000,
                    awayTeamId: 184,
                    awayTeamLongName: 'EC-KAC',
                    awayTeamShortName: 'KAC',
                    awayTeamFlavourname: 'KAC',
                    homeTeamId: 185,
                    homeTeamLongName: 'EC GRAND Immo VSV',
                    homeTeamShortName: 'VSV',
                    homeTeamFlavourname: 'VSV',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'df289e30-e870-4b8a-bc95-9d8003d91820',
                    scheduledDate: {
                      sortValue: 1616344200000,
                      value: '21.03.2021',
                      shortValue: '21.03.',
                      longValue: '21. March 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616344200000,
                    awayTeamId: 185,
                    awayTeamLongName: 'EC GRAND Immo VSV',
                    awayTeamShortName: 'VSV',
                    awayTeamFlavourname: 'VSV',
                    homeTeamId: 184,
                    homeTeamLongName: 'EC-KAC',
                    homeTeamShortName: 'KAC',
                    homeTeamFlavourname: 'KAC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '1f29353e-8158-4b20-a36d-b4cf892903d3',
                    scheduledDate: {
                      sortValue: 1616523300000,
                      value: '23.03.2021',
                      shortValue: '23.03.',
                      longValue: '23. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616523300000,
                    awayTeamId: 184,
                    awayTeamLongName: 'EC-KAC',
                    awayTeamShortName: 'KAC',
                    awayTeamFlavourname: 'KAC',
                    homeTeamId: 185,
                    homeTeamLongName: 'EC GRAND Immo VSV',
                    homeTeamShortName: 'VSV',
                    homeTeamFlavourname: 'VSV',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '87c446ff-4111-46c0-84ac-5c5201cf30af',
                    scheduledDate: {
                      sortValue: 1616782500000,
                      value: '26.03.2021',
                      shortValue: '26.03.',
                      longValue: '26. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616782500000,
                    awayTeamId: 185,
                    awayTeamLongName: 'EC GRAND Immo VSV',
                    awayTeamShortName: 'VSV',
                    awayTeamFlavourname: 'VSV',
                    homeTeamId: 184,
                    homeTeamLongName: 'EC-KAC',
                    homeTeamShortName: 'KAC',
                    homeTeamFlavourname: 'KAC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  }
                ]
              },
              {
                id: 8263,
                longname: 'QF3',
                shortname: null,
                isDecided: false,
                labels: [],
                bestOf: 7,
                gamesNeeded: 4,
                teams: [
                  {
                    id: 189,
                    longname: 'EC Red Bull Salzburg',
                    shortname: 'RBS',
                    gamesWon: 0,
                    encounterTeamStatus: 1
                  },
                  {
                    id: 191,
                    longname: 'Dornbirn Bulldogs',
                    shortname: 'DEC',
                    gamesWon: 2,
                    encounterTeamStatus: 2
                  }
                ],
                games: [
                  {
                    id: '17139c51-9eb2-45d0-8923-84f4f145d49f',
                    scheduledDate: {
                      sortValue: 1615572900000,
                      value: '12.03.2021',
                      shortValue: '12.03.',
                      longValue: '12. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '273',
                    gameDay: null,
                    gameRound: 55,
                    gameUtcTimestamp: 1615572900000,
                    awayTeamId: 191,
                    awayTeamLongName: 'Dornbirn Bulldogs',
                    awayTeamShortName: 'DEC',
                    awayTeamFlavourname: 'DEC',
                    homeTeamId: 189,
                    homeTeamLongName: 'EC Red Bull Salzburg',
                    homeTeamShortName: 'RBS',
                    homeTeamFlavourname: 'RBS',
                    homeTeamScore: 0,
                    awayTeamScore: 2,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3600,
                    gameHasEnded: true,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '0:1'
                  },
                  {
                    id: '68b32d05-1178-43f6-9e07-81314f4d1c34',
                    scheduledDate: {
                      sortValue: 1615745700000,
                      value: '14.03.2021',
                      shortValue: '14.03.',
                      longValue: '14. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '277',
                    gameDay: null,
                    gameRound: 56,
                    gameUtcTimestamp: 1615745700000,
                    awayTeamId: 189,
                    awayTeamLongName: 'EC Red Bull Salzburg',
                    awayTeamShortName: 'RBS',
                    awayTeamFlavourname: 'RBS',
                    homeTeamId: 191,
                    homeTeamLongName: 'Dornbirn Bulldogs',
                    homeTeamShortName: 'DEC',
                    homeTeamFlavourname: 'DEC',
                    homeTeamScore: 6,
                    awayTeamScore: 3,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3600,
                    gameHasEnded: true,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '2:0'
                  },
                  {
                    id: 'b706c317-788b-4957-ae07-0ebd48125790',
                    scheduledDate: {
                      sortValue: 1615918500000,
                      value: '16.03.2021',
                      shortValue: '16.03.',
                      longValue: '16. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '281',
                    gameDay: null,
                    gameRound: 57,
                    gameUtcTimestamp: 1615918500000,
                    awayTeamId: 191,
                    awayTeamLongName: 'Dornbirn Bulldogs',
                    awayTeamShortName: 'DEC',
                    awayTeamFlavourname: 'DEC',
                    homeTeamId: 189,
                    homeTeamLongName: 'EC Red Bull Salzburg',
                    homeTeamShortName: 'RBS',
                    homeTeamFlavourname: 'RBS',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'c3db6c2f-b224-4489-a7b2-459457e8db3c',
                    scheduledDate: {
                      sortValue: 1616177700000,
                      value: '19.03.2021',
                      shortValue: '19.03.',
                      longValue: '19. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '285',
                    gameDay: null,
                    gameRound: 58,
                    gameUtcTimestamp: 1616177700000,
                    awayTeamId: 189,
                    awayTeamLongName: 'EC Red Bull Salzburg',
                    awayTeamShortName: 'RBS',
                    awayTeamFlavourname: 'RBS',
                    homeTeamId: 191,
                    homeTeamLongName: 'Dornbirn Bulldogs',
                    homeTeamShortName: 'DEC',
                    homeTeamFlavourname: 'DEC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '35b431c2-1929-4283-a058-dbc8fdcd078f',
                    scheduledDate: {
                      sortValue: 1616344200000,
                      value: '21.03.2021',
                      shortValue: '21.03.',
                      longValue: '21. March 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616344200000,
                    awayTeamId: 191,
                    awayTeamLongName: 'Dornbirn Bulldogs',
                    awayTeamShortName: 'DEC',
                    awayTeamFlavourname: 'DEC',
                    homeTeamId: 189,
                    homeTeamLongName: 'EC Red Bull Salzburg',
                    homeTeamShortName: 'RBS',
                    homeTeamFlavourname: 'RBS',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '7c56268a-5ba6-4ad7-99a1-8de2899c25ae',
                    scheduledDate: {
                      sortValue: 1616523300000,
                      value: '23.03.2021',
                      shortValue: '23.03.',
                      longValue: '23. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616523300000,
                    awayTeamId: 189,
                    awayTeamLongName: 'EC Red Bull Salzburg',
                    awayTeamShortName: 'RBS',
                    awayTeamFlavourname: 'RBS',
                    homeTeamId: 191,
                    homeTeamLongName: 'Dornbirn Bulldogs',
                    homeTeamShortName: 'DEC',
                    homeTeamFlavourname: 'DEC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'f3c17f30-9280-4754-afbb-3897864a9b42',
                    scheduledDate: {
                      sortValue: 1616782500000,
                      value: '26.03.2021',
                      shortValue: '26.03.',
                      longValue: '26. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616782500000,
                    awayTeamId: 191,
                    awayTeamLongName: 'Dornbirn Bulldogs',
                    awayTeamShortName: 'DEC',
                    awayTeamFlavourname: 'DEC',
                    homeTeamId: 189,
                    homeTeamLongName: 'EC Red Bull Salzburg',
                    homeTeamShortName: 'RBS',
                    homeTeamFlavourname: 'RBS',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  }
                ]
              },
              {
                id: 8264,
                longname: 'QF4',
                shortname: null,
                isDecided: false,
                labels: [],
                bestOf: 7,
                gamesNeeded: 4,
                teams: [
                  {
                    id: 186,
                    longname: 'spusu Vienna Capitals',
                    shortname: 'VIC',
                    gamesWon: 2,
                    encounterTeamStatus: 1
                  },
                  {
                    id: 195,
                    longname: 'Hydro Fehervar AV 19',
                    shortname: 'AVS',
                    gamesWon: 0,
                    encounterTeamStatus: 2
                  }
                ],
                games: [
                  {
                    id: '7aa6cfae-8737-4358-a58e-4e398a176424',
                    scheduledDate: {
                      sortValue: 1615572900000,
                      value: '12.03.2021',
                      shortValue: '12.03.',
                      longValue: '12. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '274',
                    gameDay: null,
                    gameRound: 55,
                    gameUtcTimestamp: 1615572900000,
                    awayTeamId: 195,
                    awayTeamLongName: 'Hydro Fehervar AV 19',
                    awayTeamShortName: 'AVS',
                    awayTeamFlavourname: 'AVS',
                    homeTeamId: 186,
                    homeTeamLongName: 'spusu Vienna Capitals',
                    homeTeamShortName: 'VIC',
                    homeTeamFlavourname: 'VIC',
                    homeTeamScore: 6,
                    awayTeamScore: 1,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3600,
                    gameHasEnded: true,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '1:0'
                  },
                  {
                    id: 'c363b41c-9286-465a-8694-f10b56592bc4',
                    scheduledDate: {
                      sortValue: 1615739400000,
                      value: '14.03.2021',
                      shortValue: '14.03.',
                      longValue: '14. March 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '278',
                    gameDay: null,
                    gameRound: 56,
                    gameUtcTimestamp: 1615739400000,
                    awayTeamId: 186,
                    awayTeamLongName: 'spusu Vienna Capitals',
                    awayTeamShortName: 'VIC',
                    awayTeamFlavourname: 'VIC',
                    homeTeamId: 195,
                    homeTeamLongName: 'Hydro Fehervar AV 19',
                    homeTeamShortName: 'AVS',
                    homeTeamFlavourname: 'AVS',
                    homeTeamScore: 2,
                    awayTeamScore: 3,
                    gameStatus: 4,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 3600,
                    gameHasEnded: true,
                    labels: [
                      'FINISHED'
                    ],
                    youTubeLink: null,
                    seriesStandings: '0:2'
                  },
                  {
                    id: '8da078d6-52d0-41c8-9184-1694e4f90848',
                    scheduledDate: {
                      sortValue: 1615918500000,
                      value: '16.03.2021',
                      shortValue: '16.03.',
                      longValue: '16. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '282',
                    gameDay: null,
                    gameRound: 57,
                    gameUtcTimestamp: 1615918500000,
                    awayTeamId: 195,
                    awayTeamLongName: 'Hydro Fehervar AV 19',
                    awayTeamShortName: 'AVS',
                    awayTeamFlavourname: 'AVS',
                    homeTeamId: 186,
                    homeTeamLongName: 'spusu Vienna Capitals',
                    homeTeamShortName: 'VIC',
                    homeTeamFlavourname: 'VIC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '2e6619ff-64f5-465e-bec2-6876ee54397e',
                    scheduledDate: {
                      sortValue: 1616175000000,
                      value: '19.03.2021',
                      shortValue: '19.03.',
                      longValue: '19. March 2021'
                    },
                    scheduledTime: '18:30',
                    gameName: '286',
                    gameDay: null,
                    gameRound: 58,
                    gameUtcTimestamp: 1616175000000,
                    awayTeamId: 186,
                    awayTeamLongName: 'spusu Vienna Capitals',
                    awayTeamShortName: 'VIC',
                    awayTeamFlavourname: 'VIC',
                    homeTeamId: 195,
                    homeTeamLongName: 'Hydro Fehervar AV 19',
                    homeTeamShortName: 'AVS',
                    homeTeamFlavourname: 'AVS',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'b86c88a6-06a1-4cd7-a433-600af4797efd',
                    scheduledDate: {
                      sortValue: 1616344200000,
                      value: '21.03.2021',
                      shortValue: '21.03.',
                      longValue: '21. March 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616344200000,
                    awayTeamId: 195,
                    awayTeamLongName: 'Hydro Fehervar AV 19',
                    awayTeamShortName: 'AVS',
                    awayTeamFlavourname: 'AVS',
                    homeTeamId: 186,
                    homeTeamLongName: 'spusu Vienna Capitals',
                    homeTeamShortName: 'VIC',
                    homeTeamFlavourname: 'VIC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'e68b3582-3d0b-4c75-b59c-00f888f3d109',
                    scheduledDate: {
                      sortValue: 1616523300000,
                      value: '23.03.2021',
                      shortValue: '23.03.',
                      longValue: '23. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616523300000,
                    awayTeamId: 186,
                    awayTeamLongName: 'spusu Vienna Capitals',
                    awayTeamShortName: 'VIC',
                    awayTeamFlavourname: 'VIC',
                    homeTeamId: 195,
                    homeTeamLongName: 'Hydro Fehervar AV 19',
                    homeTeamShortName: 'AVS',
                    homeTeamFlavourname: 'AVS',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '2c08d21b-84a2-4dd2-97f1-ffa02b42e8f1',
                    scheduledDate: {
                      sortValue: 1616782500000,
                      value: '26.03.2021',
                      shortValue: '26.03.',
                      longValue: '26. March 2021'
                    },
                    scheduledTime: '19:15',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616782500000,
                    awayTeamId: 195,
                    awayTeamLongName: 'Hydro Fehervar AV 19',
                    awayTeamShortName: 'AVS',
                    awayTeamFlavourname: 'AVS',
                    homeTeamId: 186,
                    homeTeamLongName: 'spusu Vienna Capitals',
                    homeTeamShortName: 'VIC',
                    homeTeamFlavourname: 'VIC',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  }
                ]
              }
            ],
            phaseTeams: [
              {
                teamId: 193,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 184,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 186,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 189,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 195,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 191,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 28176,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 185,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 31197,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31198,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31199,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31200,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31205,
                divisionId: 8268,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31206,
                divisionId: 8268,
                isGhost: true,
                qualifyState: 0
              }
            ],
            positionX: 0,
            positionY: 0
          },
          {
            divisionId: 8265,
            divisionName: 'Semi Finals',
            divisionType: 30,
            encounters: [
              {
                id: 8266,
                longname: 'SF1',
                shortname: null,
                isDecided: false,
                labels: [],
                bestOf: 7,
                gamesNeeded: 4,
                teams: [
                  {
                    id: 31201,
                    longname: 'SF1 Team 1',
                    shortname: 'SF1 Team 1',
                    gamesWon: 0,
                    encounterTeamStatus: 1
                  },
                  {
                    id: 31202,
                    longname: 'SF1 Team 2',
                    shortname: 'SF1 Team 2',
                    gamesWon: 0,
                    encounterTeamStatus: 2
                  }
                ],
                games: [
                  {
                    id: '7248e251-8ec2-49b4-8877-85b79ed2752f',
                    scheduledDate: {
                      sortValue: 1616945400000,
                      value: '28.03.2021',
                      shortValue: '28.03.',
                      longValue: '28. March 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616945400000,
                    awayTeamId: 31202,
                    awayTeamLongName: 'SF1 Team 2',
                    awayTeamShortName: 'SF1 Team 2',
                    awayTeamFlavourname: 'SF1 Team 2',
                    homeTeamId: 31201,
                    homeTeamLongName: 'SF1 Team 1',
                    homeTeamShortName: 'SF1 Team 1',
                    homeTeamFlavourname: 'SF1 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'ecda8594-49ab-4125-b345-7b83ec8b52f4',
                    scheduledDate: {
                      sortValue: 1617084540000,
                      value: '30.03.2021',
                      shortValue: '30.03.',
                      longValue: '30. March 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617084540000,
                    awayTeamId: 31201,
                    awayTeamLongName: 'SF1 Team 1',
                    awayTeamShortName: 'SF1 Team 1',
                    awayTeamFlavourname: 'SF1 Team 1',
                    homeTeamId: 31202,
                    homeTeamLongName: 'SF1 Team 2',
                    homeTeamShortName: 'SF1 Team 2',
                    homeTeamFlavourname: 'SF1 Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '9575ef94-6246-4f68-b899-4e68e3a6c9a0',
                    scheduledDate: {
                      sortValue: 1617257340000,
                      value: '01.04.2021',
                      shortValue: '01.04.',
                      longValue: '01. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617257340000,
                    awayTeamId: 31202,
                    awayTeamLongName: 'SF1 Team 2',
                    awayTeamShortName: 'SF1 Team 2',
                    awayTeamFlavourname: 'SF1 Team 2',
                    homeTeamId: 31201,
                    homeTeamLongName: 'SF1 Team 1',
                    homeTeamShortName: 'SF1 Team 1',
                    homeTeamFlavourname: 'SF1 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '97e0b54b-5454-4a72-a786-aa7b4fa51339',
                    scheduledDate: {
                      sortValue: 1617430140000,
                      value: '03.04.2021',
                      shortValue: '03.04.',
                      longValue: '03. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617430140000,
                    awayTeamId: 31201,
                    awayTeamLongName: 'SF1 Team 1',
                    awayTeamShortName: 'SF1 Team 1',
                    awayTeamFlavourname: 'SF1 Team 1',
                    homeTeamId: 31202,
                    homeTeamLongName: 'SF1 Team 2',
                    homeTeamShortName: 'SF1 Team 2',
                    homeTeamFlavourname: 'SF1 Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '8f0c0aff-3618-40ce-bda3-9b92370d3794',
                    scheduledDate: {
                      sortValue: 1617643800000,
                      value: '05.04.2021',
                      shortValue: '05.04.',
                      longValue: '05. April 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617643800000,
                    awayTeamId: 31202,
                    awayTeamLongName: 'SF1 Team 2',
                    awayTeamShortName: 'SF1 Team 2',
                    awayTeamFlavourname: 'SF1 Team 2',
                    homeTeamId: 31201,
                    homeTeamLongName: 'SF1 Team 1',
                    homeTeamShortName: 'SF1 Team 1',
                    homeTeamFlavourname: 'SF1 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'b45664b5-48a7-450e-9047-1ff834e43710',
                    scheduledDate: {
                      sortValue: 1617775740000,
                      value: '07.04.2021',
                      shortValue: '07.04.',
                      longValue: '07. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617775740000,
                    awayTeamId: 31201,
                    awayTeamLongName: 'SF1 Team 1',
                    awayTeamShortName: 'SF1 Team 1',
                    awayTeamFlavourname: 'SF1 Team 1',
                    homeTeamId: 31202,
                    homeTeamLongName: 'SF1 Team 2',
                    homeTeamShortName: 'SF1 Team 2',
                    homeTeamFlavourname: 'SF1 Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'd1130912-ecfc-42d2-bc5b-58053bd6bdba',
                    scheduledDate: {
                      sortValue: 1617948540000,
                      value: '09.04.2021',
                      shortValue: '09.04.',
                      longValue: '09. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617948540000,
                    awayTeamId: 31202,
                    awayTeamLongName: 'SF1 Team 2',
                    awayTeamShortName: 'SF1 Team 2',
                    awayTeamFlavourname: 'SF1 Team 2',
                    homeTeamId: 31201,
                    homeTeamLongName: 'SF1 Team 1',
                    homeTeamShortName: 'SF1 Team 1',
                    homeTeamFlavourname: 'SF1 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  }
                ]
              },
              {
                id: 8267,
                longname: 'SF2',
                shortname: null,
                isDecided: false,
                labels: [],
                bestOf: 7,
                gamesNeeded: 4,
                teams: [
                  {
                    id: 31203,
                    longname: 'SF2 Team 1',
                    shortname: 'SF2 Team 1',
                    gamesWon: 0,
                    encounterTeamStatus: 1
                  },
                  {
                    id: 31204,
                    longname: 'SF2 Team 2',
                    shortname: 'SF2 Team 2',
                    gamesWon: 0,
                    encounterTeamStatus: 2
                  }
                ],
                games: [
                  {
                    id: '6d129c10-8f1d-4ea8-acfb-e6d434b3222c',
                    scheduledDate: {
                      sortValue: 1616945400000,
                      value: '28.03.2021',
                      shortValue: '28.03.',
                      longValue: '28. March 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1616945400000,
                    awayTeamId: 31204,
                    awayTeamLongName: 'SF2 Team 2',
                    awayTeamShortName: 'SF2 Team 2',
                    awayTeamFlavourname: 'SF2 Team 2',
                    homeTeamId: 31203,
                    homeTeamLongName: 'SF2 Team 1',
                    homeTeamShortName: 'SF2 Team 1',
                    homeTeamFlavourname: 'SF2 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'ba4bc323-c0bc-4192-a4d8-4966be30ef19',
                    scheduledDate: {
                      sortValue: 1617084540000,
                      value: '30.03.2021',
                      shortValue: '30.03.',
                      longValue: '30. March 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617084540000,
                    awayTeamId: 31203,
                    awayTeamLongName: 'SF2 Team 1',
                    awayTeamShortName: 'SF2 Team 1',
                    awayTeamFlavourname: 'SF2 Team 1',
                    homeTeamId: 31204,
                    homeTeamLongName: 'SF2 Team 2',
                    homeTeamShortName: 'SF2 Team 2',
                    homeTeamFlavourname: 'SF2 Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '42c1dd96-4708-430f-b2a3-9e88ee7b1409',
                    scheduledDate: {
                      sortValue: 1617257340000,
                      value: '01.04.2021',
                      shortValue: '01.04.',
                      longValue: '01. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617257340000,
                    awayTeamId: 31204,
                    awayTeamLongName: 'SF2 Team 2',
                    awayTeamShortName: 'SF2 Team 2',
                    awayTeamFlavourname: 'SF2 Team 2',
                    homeTeamId: 31203,
                    homeTeamLongName: 'SF2 Team 1',
                    homeTeamShortName: 'SF2 Team 1',
                    homeTeamFlavourname: 'SF2 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '054b077f-ddfb-4f64-9497-8c9c9d8e753d',
                    scheduledDate: {
                      sortValue: 1617430140000,
                      value: '03.04.2021',
                      shortValue: '03.04.',
                      longValue: '03. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617430140000,
                    awayTeamId: 31203,
                    awayTeamLongName: 'SF2 Team 1',
                    awayTeamShortName: 'SF2 Team 1',
                    awayTeamFlavourname: 'SF2 Team 1',
                    homeTeamId: 31204,
                    homeTeamLongName: 'SF2 Team 2',
                    homeTeamShortName: 'SF2 Team 2',
                    homeTeamFlavourname: 'SF2 Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '8039bd9b-f8e0-4324-8e30-a3f4d39bab96',
                    scheduledDate: {
                      sortValue: 1617643800000,
                      value: '05.04.2021',
                      shortValue: '05.04.',
                      longValue: '05. April 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617643800000,
                    awayTeamId: 31204,
                    awayTeamLongName: 'SF2 Team 2',
                    awayTeamShortName: 'SF2 Team 2',
                    awayTeamFlavourname: 'SF2 Team 2',
                    homeTeamId: 31203,
                    homeTeamLongName: 'SF2 Team 1',
                    homeTeamShortName: 'SF2 Team 1',
                    homeTeamFlavourname: 'SF2 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '66bc503f-c1e8-44b5-be7a-c256a4367f44',
                    scheduledDate: {
                      sortValue: 1617775740000,
                      value: '07.04.2021',
                      shortValue: '07.04.',
                      longValue: '07. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617775740000,
                    awayTeamId: 31203,
                    awayTeamLongName: 'SF2 Team 1',
                    awayTeamShortName: 'SF2 Team 1',
                    awayTeamFlavourname: 'SF2 Team 1',
                    homeTeamId: 31204,
                    homeTeamLongName: 'SF2 Team 2',
                    homeTeamShortName: 'SF2 Team 2',
                    homeTeamFlavourname: 'SF2 Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: '3ff777ff-b370-48f0-8023-52e1ce0fb832',
                    scheduledDate: {
                      sortValue: 1617948540000,
                      value: '09.04.2021',
                      shortValue: '09.04.',
                      longValue: '09. April 2021'
                    },
                    scheduledTime: '08:09',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1617948540000,
                    awayTeamId: 31204,
                    awayTeamLongName: 'SF2 Team 2',
                    awayTeamShortName: 'SF2 Team 2',
                    awayTeamFlavourname: 'SF2 Team 2',
                    homeTeamId: 31203,
                    homeTeamLongName: 'SF2 Team 1',
                    homeTeamShortName: 'SF2 Team 1',
                    homeTeamFlavourname: 'SF2 Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: true,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  }
                ]
              }
            ],
            phaseTeams: [
              {
                teamId: 193,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 184,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 186,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 189,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 195,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 191,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 28176,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 185,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 31197,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31198,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31199,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31200,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31205,
                divisionId: 8268,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31206,
                divisionId: 8268,
                isGhost: true,
                qualifyState: 0
              }
            ],
            positionX: 0,
            positionY: 0
          },
          {
            divisionId: 8268,
            divisionName: 'Finals',
            divisionType: 30,
            encounters: [
              {
                id: 8269,
                longname: 'Final',
                shortname: null,
                isDecided: false,
                labels: [],
                bestOf: 7,
                gamesNeeded: 4,
                teams: [
                  {
                    id: 31207,
                    longname: 'Final Team 1',
                    shortname: 'Final Team 1',
                    gamesWon: 0,
                    encounterTeamStatus: 1
                  },
                  {
                    id: 31208,
                    longname: 'Final Team 2',
                    shortname: 'Final Team 2',
                    gamesWon: 0,
                    encounterTeamStatus: 2
                  }
                ],
                games: [
                  {
                    id: '97e17134-a5ce-4ece-bd84-9b5588b4c22f',
                    scheduledDate: {
                      sortValue: 1618155000000,
                      value: '11.04.2021',
                      shortValue: '11.04.',
                      longValue: '11. April 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1618155000000,
                    awayTeamId: 31208,
                    awayTeamLongName: 'Final Team 2',
                    awayTeamShortName: 'Final Team 2',
                    awayTeamFlavourname: 'Final Team 2',
                    homeTeamId: 31207,
                    homeTeamLongName: 'Final Team 1',
                    homeTeamShortName: 'Final Team 1',
                    homeTeamFlavourname: 'Final Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'e6965e80-4719-4a9e-9fdf-60f8c27b260e',
                    scheduledDate: {
                      sortValue: 1618335000000,
                      value: '13.04.2021',
                      shortValue: '13.04.',
                      longValue: '13. April 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1618335000000,
                    awayTeamId: 31207,
                    awayTeamLongName: 'Final Team 1',
                    awayTeamShortName: 'Final Team 1',
                    awayTeamFlavourname: 'Final Team 1',
                    homeTeamId: 31208,
                    homeTeamLongName: 'Final Team 2',
                    homeTeamShortName: 'Final Team 2',
                    homeTeamFlavourname: 'Final Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'df37aea4-5ddb-44f0-94e2-ef47fc9cb69d',
                    scheduledDate: {
                      sortValue: 1618594200000,
                      value: '16.04.2021',
                      shortValue: '16.04.',
                      longValue: '16. April 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1618594200000,
                    awayTeamId: 31208,
                    awayTeamLongName: 'Final Team 2',
                    awayTeamShortName: 'Final Team 2',
                    awayTeamFlavourname: 'Final Team 2',
                    homeTeamId: 31207,
                    homeTeamLongName: 'Final Team 1',
                    homeTeamShortName: 'Final Team 1',
                    homeTeamFlavourname: 'Final Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'e2e00e25-46b9-44aa-9b30-532e85183614',
                    scheduledDate: {
                      sortValue: 1618759800000,
                      value: '18.04.2021',
                      shortValue: '18.04.',
                      longValue: '18. April 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1618759800000,
                    awayTeamId: 31207,
                    awayTeamLongName: 'Final Team 1',
                    awayTeamShortName: 'Final Team 1',
                    awayTeamFlavourname: 'Final Team 1',
                    homeTeamId: 31208,
                    homeTeamLongName: 'Final Team 2',
                    homeTeamShortName: 'Final Team 2',
                    homeTeamFlavourname: 'Final Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'e0e74931-23b3-4a9c-9476-f180981b3ed5',
                    scheduledDate: {
                      sortValue: 1618939800000,
                      value: '20.04.2021',
                      shortValue: '20.04.',
                      longValue: '20. April 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1618939800000,
                    awayTeamId: 31208,
                    awayTeamLongName: 'Final Team 2',
                    awayTeamShortName: 'Final Team 2',
                    awayTeamFlavourname: 'Final Team 2',
                    homeTeamId: 31207,
                    homeTeamLongName: 'Final Team 1',
                    homeTeamShortName: 'Final Team 1',
                    homeTeamFlavourname: 'Final Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'ac61b10b-1f27-4c3b-ad46-e722b77d5a5b',
                    scheduledDate: {
                      sortValue: 1619199000000,
                      value: '23.04.2021',
                      shortValue: '23.04.',
                      longValue: '23. April 2021'
                    },
                    scheduledTime: '19:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1619199000000,
                    awayTeamId: 31207,
                    awayTeamLongName: 'Final Team 1',
                    awayTeamShortName: 'Final Team 1',
                    awayTeamFlavourname: 'Final Team 1',
                    homeTeamId: 31208,
                    homeTeamLongName: 'Final Team 2',
                    homeTeamShortName: 'Final Team 2',
                    homeTeamFlavourname: 'Final Team 2',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  },
                  {
                    id: 'a49f20da-8227-455d-aa7d-9fe58282765b',
                    scheduledDate: {
                      sortValue: 1619364600000,
                      value: '25.04.2021',
                      shortValue: '25.04.',
                      longValue: '25. April 2021'
                    },
                    scheduledTime: '17:30',
                    gameName: '',
                    gameDay: null,
                    gameRound: null,
                    gameUtcTimestamp: 1619364600000,
                    awayTeamId: 31208,
                    awayTeamLongName: 'Final Team 2',
                    awayTeamShortName: 'Final Team 2',
                    awayTeamFlavourname: 'Final Team 2',
                    homeTeamId: 31207,
                    homeTeamLongName: 'Final Team 1',
                    homeTeamShortName: 'Final Team 1',
                    homeTeamFlavourname: 'Final Team 1',
                    homeTeamScore: 0,
                    awayTeamScore: 0,
                    gameStatus: 0,
                    extendedStatus: 0,
                    dateIsToBeDetermined: false,
                    timeIsToBeDetermined: false,
                    isOvertime: false,
                    isShootOut: false,
                    liveTime: 0,
                    gameHasEnded: false,
                    labels: [],
                    youTubeLink: null,
                    seriesStandings: null
                  }
                ]
              }
            ],
            phaseTeams: [
              {
                teamId: 193,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 184,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 186,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 189,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 195,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 191,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 28176,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 185,
                divisionId: 8260,
                isGhost: false,
                qualifyState: 0
              },
              {
                teamId: 31197,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31198,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31199,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31200,
                divisionId: 8265,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31205,
                divisionId: 8268,
                isGhost: true,
                qualifyState: 0
              },
              {
                teamId: 31206,
                divisionId: 8268,
                isGhost: true,
                qualifyState: 0
              }
            ],
            positionX: 0,
            positionY: 0
          }
        ],
        divisionId: 8259
      },
      lastUpdate: {
        formattedShort: '14.03.21 22:25',
        formattedLong: '14.March 2021 22:25',
        timestamp: 1615757159214,
        value: '2021-03-14 22:25'
      }
    };
  }
}
